name: CI

on:
  pull_request:

jobs:
  check:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo check
        run: cargo check --locked --workspace

  fmt:
    name: Cargo format
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo clippy --no-deps -- -D warnings
